In [2]:
# import requests

# # Importing notebook with annotations

# url = 'https://raw.githubusercontent.com/hamidov9jat/zero-to-mastery-ml/master/section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb'
# r = requests.get(url, allow_redirects=True)
# open('introduction-to-numpy.ipynb', 'wb').write(r.content)

# # Importing notebook from video

# url = 'https://raw.githubusercontent.com/hamidov9jat/zero-to-mastery-ml/master/section-2-data-science-and-ml-tools/introduction-to-numpy-video.ipynb'
# r = requests.get(url, allow_redirects=True)
# open('introduction-to-numpy-video.ipynb', 'wb').write(r.content)

# # Importing exercise notebook

# url = 'https://raw.githubusercontent.com/hamidov9jat/zero-to-mastery-ml/master/section-2-data-science-and-ml-tools/numpy-exercises.ipynb'
# r = requests.get(url, allow_redirects=True)
# open('numpy-exercises.ipynb', 'wb').write(r.content)

# # Importing solutions notebook

# url = 'https://raw.githubusercontent.com/hamidov9jat/zero-to-mastery-ml/master/section-2-data-science-and-ml-tools/numpy-exercises-solutions.ipynb'
# r = requests.get(url, allow_redirects=True)
# open('numpy-exercises-solutions.ipynb', 'wb').write(r.content)

29623

In [3]:
import numpy as np

# 1. Data Types & Attributes

In [4]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
    ]
    
])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1

array([1, 2, 3])

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1.ndim

1

In [17]:
a2.ndim

2

In [18]:
a3.ndim

3

In [20]:
a1.dtype

dtype('int32')

In [21]:
a2.dtype

dtype('float64')

In [22]:
a3.dtype

dtype('int32')

In [26]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [23]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [24]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [25]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
# Create a Dataframe from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5